Makefile, hack/make-bundle-vars.mk
replacing ODF with OCO (ocs-client-operator) and replacing openshift-storage with ocs-client-operator-system namespace as that is the one used in yaml files.
Signed-off-by: Madhu Rajanna <madhupr007@gmail.com>
=> cleanup: replace ODF with OCO

controllers/clusterversion_controller.go, controllers/storageclient_controller.go
This commit blocks the creation of multiple storageclients for the same provider and allows the creation of multiple storageclients in the same namespace.
fixes: #9
=> Allow multiple storageclients per namespace

Makefile, config/manifests/fusion/kustomization.yaml, hack/make-bundle-vars.mk
This PR adds a kustomization file to patch the base CSV with content for fusion bundle. It overwrites the default bundle and reuses default Dockerfiles for bundle generation and build. We do not commit these updated changes to git.
=> bundle: enable bundle generation for fusion

images.yaml
Use the openshift registry to pull the ocp sidecar images and odf reqistry to pull odf cephcsi and sidecar image.
cc @nb-ohad 
cc @jarrpa
=> csi: use openshift registry to pull ocp images

Makefile, hack/gen-csi-images-manifest.sh, hack/make-bundle-vars.mk
I did a fair amount of testing on this, so I'm fairly confident this should work out. Key thing to note is that despite the somewhat long list of new variables most of them can be safely left alone or ignored during normal development. For the purposes of multi-version build automation the important variables are those of the format `CSI_IMG_<SIDECAR>_<VERSION>` where SIDECAR is the relevant CSI sidecar container and VERSION is the target version of OCP.
Signed-off-by: Jose A. Rivera <jarrpa@redhat.com>
=> makefile: add make target and variables to specify CSI images

bundle/manifests/ocs-client-operator.clusterserviceversion.yaml, config/manager/manager.yaml, controllers/storageclassclaim_controller.go
This PR contains two fixes
* Increase the resource limit to fix the OOMKilled problem
* remove the code which generates the subvolumegroup name if its present in the RPC call.
=> Fix bugs found in migration of ODF to ocs-client-operator

bundle/manifests/ocs-client-operator.clusterserviceversion.yaml, config/manifests/bases/kustomization.yaml
This operator is not supposed to be directly installed from the operator hub, and the agent is supposed to install it, Hiding the operator from the operator hub for the same reason.
=> bundle: hide operator from the operatorhub

bundle/manifests/ocs-client-operator.clusterserviceversion.yaml, config/rbac/kustomization.yaml, service/status-report/main.go
- Add missing ClusterVersion and ClusterServiceVersion APIs to status reporter Scheme
- Add missing Role and RoleBinding to Kustomize and generate CSV Bundle
=> Bug 2247737: add APIs to scheme, role and role binding to bundle

controllers/storageclient_controller.go
Fixes the issue created where consecutive CronJobs iterations create pods unnecessarily and caused maxPod limit to be reached thus resulting in future pods scheduling to be stuck in a pending state.
* Added a ConcurrencyPolicy field to the CronJob for reconcileClientStatusReporterJob in StorageClientReconciler
* ConcurrencyPolicy chosen in this case to be `Forbid`
The `Forbid` option specifies waiting for the current job to finish before starting a new one and the `Replace` option starts a new job no matter what is the current one's status is (which can also create a new pod while the previous job’s pod is still terminating and increase pod count unnecessarily).
Since the created pod for this cronJob purpose is a heartbeat to the provider server i don't see the point in choosing to …
=> Bug 2247748: A storage-client CronJob create too many jobs and pods causing maxPod limit to be reached

pkg/csi/cephfsdaemonset.go, pkg/csi/rbddaemonset.go, pkg/utils/k8sutils.go, pkg/utils/placements.go
Adding toleration to schedule CSI pods on master nodes
=> Bug 2247735: Adding toleration to schedule CSI pods on master nodes

pkg/console/console.go
- Updates console name to align with the UI plugin build name
Fixes https://github.com/red-hat-storage/ocs-client-operator/issues/45
=> console: fixes console plugin name

bundle/manifests/ocs-client-operator.clusterserviceversion.yaml, config/manifests/bases/kustomization.yaml
remove non-standalone annotation from the CSV so that the operator can be visible in the UI.
=> remove non-standalone annotation

controllers/clusterversion_controller.go, pkg/csi/csi.go
pick the csi sidecar images version that are best suitable for the platform
=> controllers: pick next best version of csi images

config/crd/bases/ocs.openshift.io_storageclassclaims.yaml, config/crd/bases/ocs.openshift.io_storageclients.yaml, config/rbac/role.yaml, hack/make-bundle-vars.mk, hack/make-tools.mk
To add the XValidation we need to update the controller-gen version.
Hence updating it to the latest 0.9.x version
=> makefile: update controller gen version

pkg/csi/rbddeployment.go, pkg/templates/csisidecars.go, pkg/templates/defaults.go
RBD Provisioner was missing csi-addons sidecar, adding it in this PR
Ref for CSI-Addons Sidecar: [container config](https://github.com/rook/rook/blob/master/pkg/operator/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml#L140-L180)
=> csi: add csi-addon sidecar to the rbd provisioner deployment

controllers/clusterversion_controller.go
Ownership enforcement is occurring after the DeepCopy method and causing the created ceph resources to be spawned without an owner.
=> Change ownership logic to enforce after the DeepCopy

action.yaml
create an action.yaml file for setting up golang and reuse in github workflows wherever golang installation is required.
=> ci: use action.yaml for setting up go during CI

controllers/clusterversion_controller.go, pkg/csi/cephfsdaemonset.go, pkg/csi/cephfsdeployment.go, pkg/csi/rbddaemonset.go, pkg/csi/rbddeployment.go, pkg/csi/scc.go, pkg/templates/csidriver.go, pkg/templates/csisidecars.go
The existing code is very wasteful regarding memory management of large in-memory structures. On each reconcile cycle multiple big nested structures are either fully or partially copied multiple times and in multiple locations in the codebase. This creates unnecessary pressure on the garbage collector and wastes multiple CPU cycles moving around the same bits
A second side effect of the current code structure is the creation of a fresh nested set of objects on every reconcile cycle that overwrites any metadata on existing objects. This results in a contributor’s need to be very careful and consider the order of operations when writing reconciliation functions for CSI resources. As an example, I can give the fact that the current code contains a bug where all of the owner references on CSI …
=> Refactor CSI package code to reduce memory, GC overhead, and "order of operations" considerations

pkg/csi/cephfsdaemonset.go, pkg/csi/cephfsdeployment.go, pkg/csi/rbddaemonset.go, pkg/csi/rbddeployment.go, pkg/utils/k8sutils.go
- fix the labels on deployment & daemonset resources
- add object meta to pod template spec for correct deployment
- create labels map if doesn't exist avoiding panic
there's a li'l pesky bug unrelated to current changeset as in the func createorupdate always updating the deployment & daemonset resources.
can be seen in the GH comments marked testing.
=> controllers: deploy csi correctly by adding labels

controllers/storageclassclaim_controller.go, pkg/utils/k8sutils.go, service/status-report/main.go
provider sends it's subscription channel name as response to client heartbeat, we will store that in the corresponding storageclient as an annotation value.
this will help in making upgrade decisions going forward.
part of [RHSTOR-5496]
=> store desired subscription channel as annotation on storageclient CR

config/manager/kustomization.yaml, config/manager/manager.yaml, config/manager/webhook_service.yaml, config/rbac/role.yaml, config/rbac/status-reporter-clusterrole.yaml, controllers/clusterversion_controller.go, controllers/storageclient_controller.go, main.go, pkg/templates/validatingwebhook.go, pkg/utils/k8sutils.go, pkg/webhook/subscription.go, service/status-report/main.go
provider sends it's subscription channel name as response to client heartbeat, we will store that in the corresponding storageclient as an annotation value.
implement a webhook server that validates whether the channel name in the subscription routed to it conforms to all the storageclients desired operator subscription placed on the storageclient as an annotation value.
after controller start up we register webhook and also label the subscription which ensures only updates on that specific subscription are routed to the webhook.
part of [RHSTOR-5496]
Depends on #89
=> implement webhook for validating ocs-client-operator subscription channel

config/default/manager_auth_proxy_patch.yaml
In Kustomization we are trying to replace a image w/ name `kube-rbac-proxy` during build time, however rather than the placeholder the deployment has original image name & tag which makes update of rbac proxy image not possible via Makefile.
In d/s an hack is employed to directly change the value in resulting csv manifests and this PR fixes that providing a way to respect values set via Makefile.
=> Fix placeholder kube-rbac-proxy image to respect supplied image during build time

bundle/manifests/ocs-client-operator-config_v1_configmap.yaml, bundle/manifests/ocs-client-operator-webhook-server_v1_service.yaml, bundle/manifests/ocs-client-operator.clusterserviceversion.yaml, bundle/manifests/ocs.openshift.io_storageclaims.yaml, config/rbac/role.yaml, hack/make-bundle-vars.mk
the generated bundle is out of sync w/ the config & manifests, even though they can be rebuilt we can have the bundle fully removed or keep it upto date from time to time, this PR does the latter.
for some of the controllers kubebuilder tags were added but it wasn't updated in the config and so syncing everything once.
=> update bundle w/ bumping version

bundle/metadata/dependencies.yaml, config/metadata/dependencies.yaml, hack/make-bundle-vars.mk
since we are going to be installed alongside w/ odf-operator inorder to conform to u/s CI changing the dependency of csi-addons from 0.5.0 to 0.8.0
=> update csi-addons dependency from 0.5.0 to 0.8.0

controllers/storageclaim_controller.go
during first reconcile of storageclaim, storageclass will not exist and so `claimType` will have zero value which is being set inside a conditional and fails type check in switch statement as this var was reused.
=> controllers: define claimType before getting storageclass

config/rbac/status-reporter-clusterrole.yaml, service/status-report/main.go
- Completion of the debts from the TODOs in #127
- Revises permissions to include all CMs accessed by `status-reporter`
[RHSTOR-5500](https://issues.redhat.com/browse/RHSTOR-5500)
=> Refactors status Setters and restricts RBAC

config/rbac/status-reporter-clusterrole.yaml, service/status-report/main.go
On hosted cluster value of 
`k get cm cluster-config-v1 -nkube-system -ojsonpath='{.data.install\-config}' | yq -r .metadata.name` is empty.  
Hence, It has been decided to display the base domain regardless of whether it's an HCP or OCP cluster.
=> Setting basedomain as cluster name

bundle/manifests/ocs-client-operator.clusterserviceversion.yaml, config/rbac/status-reporter-clusterrole.yaml
api resource name always is plural but we had incorrect rbac as `dns` and it should be `dnses`. For other change, `rook-ceph-mon-endpoints` is a name at provider end and in client cluster it is stored as `ceph-csi-configs`.
The regression was introduced when we restricted the rbac to specific resources at cluster role.
=> bundle: update missing and incorrect rbac resources

bundle/manifests/ocs-client-operator.clusterserviceversion.yaml, config/manifests/bases/ocs-client-operator.clusterserviceversion.yaml
add the annotation operators.operatorframework.io/internal-objects to the operator csv to make storageClaim internal/ to remove it from the console
Ref: https://docs.openshift.com/container-platform/4.15/operators/operator_sdk/osdk-generating-csvs.html#osdk-hiding-internal-objects_osdk-generating-csvs
=> add annotation to csv to make storageclaim internal

bundle/manifests/ocs-client-operator.clusterserviceversion.yaml, config/rbac/role.yaml, controllers/clusterversion_controller.go
rbac generation was affected because of this typo
The bug was introduced in this [PR](https://github.com/red-hat-storage/ocs-client-operator/pull/152)
=> BUG 2276565: controllers: fixed typo subscription to subscriptions

Dockerfile, bundle/manifests/ocs-client-operator.clusterserviceversion.yaml, bundle/manifests/ocs.openshift.io_storageclaims.yaml, bundle/manifests/ocs.openshift.io_storageclients.yaml, config/crd/bases/ocs.openshift.io_storageclaims.yaml, config/crd/bases/ocs.openshift.io_storageclients.yaml, config/rbac/role.yaml, controllers/storageclaim_controller.go, go.mod, hack/make-bundle-vars.mk, hack/make-project-vars.mk, hack/make-tools.mk
- golang from 1.21 to 1.22
- CSV from 4.16 to 4.17
- controller-gen from 0.9.2 to 0.15.0
- golang lint from 1.56.2 to 1.59.1
- fix a redundant check based on updated linter
=> bundle: update build tools and versions

.github/workflows/golangci-lint.yaml, hack/build.env, hack/make-project-vars.mk
occasionally lint version used in CI (latest by default) gets ahead of version used locally, in addition to that, PRs against branches also are checked against latest linter which often forces to update unrelated parts of backports, this PR tries to always read the version from local vars and use that in CI.
=> ci: use golangci-lint version from makefile

.github/workflows/docker-push.yaml
relates to red-hat-storage/ocs-operator#2616, when ocs or odf operator is deployed by u/s CI they try to pull a preconfigured bundle of ocs-client-operator for deployment however that bundle is being created on demand manually.
Having a working gh-action for performing that op reduces manual work, at the same time trying to keep the action as short as possible we should set the vars correctly that corresponds to a particular release in Makefile.
Below is an example on how it was done manually
```
export VERSION=4.16.0
export IMG=quay.io/ocs-dev/ocs-client-operator:v${VERSION}
export OCS_CLIENT_CONSOLE_IMG=\
quay.io/ocs-dev/ocs-client-console:v4.15.0
export BUNDLE_IMG=quay.io/ocs-dev/ocs-client-operator-bundle:v${VERSION}
```
Apart from above, client-op depends on csi-addons and for u/s, …
=> action: update docker-push action for pushing images on demand

.github/workflows/verify-generated.yaml, Makefile, hack/godeps-verify.sh
update Make file to add new targets to verify go deps and add it in the github action
=> hack: add verification of go deps in gh action

internal/controller/storageclaim_controller.go, pkg/utils/k8sutils.go
This PR adds the required EncrpytionKeyRotation annotations on RBD StorageClasses to automate key rotation operations.
The default schedule is: weekly
=> RHSTOR-5883: Annotate RBD storageclasses for EncryptionKeyRotation

Dockerfile, Makefile, bundle.Dockerfile, bundle/manifests/ocs-client-operator.clusterserviceversion.yaml, bundle/metadata/annotations.yaml, config/console/console_init.yaml, config/console/kustomization.yaml, config/manager/kustomization.yaml, config/manager/manager.yaml, config/rbac/role.yaml, hack/go-build.sh, internal/controller/operatorconfigmap_controller.go, service/deployment-guard/main.go
we want to run manager only when required, i.e, we are going to reconcile and manage CSI among other operands. we are achieving that by adding an init container which only get successful if client-operator is deployed standalone or running in provider configured odf cluster.
Depends on: red-hat-storage/ocs-operator#2717
ref: red-hat-storage/odf-operator#450
=> init container to decide allowing reconciliation of manager

pkg/utils/csi.go
by default delegate CSI management to ceph-csi-operator and only reconcile them directly if the env is set to `self`
=> controllers: deploy CSI if opted in

service/deployment-guard/main.go
when we are running alongside odf-operator the CRDs corresponding to an operator is installed first however it isn't guaranteed that CRDs of all dependent operators are installed first before deploying any CSV.
Due to above, StorageCluster CRD is sometimes created after we check for it's existence and 1 min is the delay observed when client-op is listed first and ocs-op listed last in the install plan for deploying CSVs.
Please note this should be temporary upto when we develop new operator which directly installs other operators based on runtime requirements outside of OLM.
This PR imposes a mandatory wait time for standalone client-op installs.
=> controllers: wait for 90 sec before checking StorageCluster CRD

pkg/templates/csi.go
Depends on: red-hat-storage/ceph-csi-operator#24
=> csi: change SA name in csi SCCs

Makefile, bundle/manifests/ocs-client-operator.clusterserviceversion.yaml, bundle/metadata/dependencies.yaml, config/metadata/dependencies.yaml, hack/make-bundle-vars.mk
csi-addons 0.9.0 introduced a regression in their deployments by adding an extra prefix and 0.9.1 fixes that
=> makefile: update csi-addons bundle version from 0.9.0 to 0.9.1

internal/controller/operatorconfigmap_controller.go
Disable env var default return value to false in order to not force noobaa management on the client while feature is in dev preview
=> Disable noobaa management on client for dev preview

config/manifests/bases/ocs-client-operator.clusterserviceversion.yaml
Levels defined:
1 - Basic Install
2 - Seamless Upgrades
3 - Full Lifecycle Management
4 - Deep Insights
5 - Autopilot
ocs & odf are on 4, client also ticks those boxes indirectly as the info sent from client is the main basis for alerting on provider and so choosing the same level.
Fix for bug https://bugzilla.redhat.com/show_bug.cgi?id=2303821
=> bundle: add capabilities to csv

config/console/console_init.yaml, config/manager/manager.yaml, internal/controller/storageclient_controller.go
all operators deployed as part of odf should tolerate this taint by default "node.ocs.openshift.io/storage=true:NoSchedule"
=> bundle: add default toleration to operators and cronjob

internal/controller/storageclient_controller.go
Introduced in https://github.com/red-hat-storage/ocs-client-operator/pull/176 the storage client controller is trying to create a secret with non existent storage client namespace name. This patch fixes the above by providing operator namespace instead.
=> controllers: Fix secret creation in storageclient controller

.github/workflows/verify-generated.yaml, Makefile, hack/update-csv-timestamp.sh
This PR includes the following changes
1. add a script not to update the timestamp in the csv if there are no bundle changes
2. add ci action to verify bundle changes
With operator-sdk 1.26+ every time we generate a new bundle, the createdAt field in the csv is updated. 
This means we have to create a manual backport even when there are no bundle changes hence, resetting the createdAt field if there are no changes in the bundle.
This PR also introduces a ci action to check whether there are any uncommitted bundle changes.
=> hack: update csv timestamp only when there are changes in bundle

pkg/templates/csi.go
all components deployed as part of odf should tolerate this taint by default "node.ocs.openshift.io/storage=true:NoSchedule"
=> controllers: add ocs default toleration to csi driver spec

Dockerfile, bundle/manifests/ocs-client-operator.clusterserviceversion.yaml, cmd/main.go, config/rbac/role.yaml, internal/controller/storageclaim_controller.go, pkg/utils/predicates.go
The PR does the following
1. gcr.io/distroless/static:nonroot does not allow us to run
bash scripts, since with available crd we are capturing the exit
via a bash script, moving to use
registry.access.redhat.com/ubi9/ubi-minimal as the base
2. remove caching only storageCluster crd
3. fix panic while logging
=> controllers: fix available crd

bundle/manifests/ocs-client-operator.clusterserviceversion.yaml, config/rbac/status-reporter-clusterrole.yaml, internal/controller/storageclient_controller.go, pkg/utils/k8sutils.go, service/status-report/main.go
- Adding a cluster role to get the cluster resource quota from a status reporter
- the name of CRQ is not always same as storage client so changing the logic as per the format
=> api: adding role and set correct name to get CRQ

bundle/manifests/ocs-client-operator-config_v1_configmap.yaml, bundle/manifests/ocs-client-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, internal/controller/operatorconfigmap_controller.go
The csi-omap generator needs to the enabled on the application cluster for RDR. 
Add a new key to operator configMap controller to enable omap. If the key is not set we will always enable this option on operator Config CR. If key is available we will set the value to what was provider in `ocs-client-operator-config`
=> csi: enable csi-omap based on key in operator config

internal/controller/storageclaim_controller.go
Adding the ownerRef that was missed as a part of https://github.com/red-hat-storage/ocs-client-operator/pull/266
=> controllers: add missing owner on sc and vsc

internal/controller/storageclaim_controller.go
Set the VRC names from the provider.
Followup for: https://github.com/red-hat-storage/ocs-client-operator/pull/276
=> controllers: set the vrc name to what we get from provider

api/v1alpha1/storageclient_types.go, bundle/manifests/ocs-client-operator.clusterserviceversion.yaml, bundle/manifests/ocs.openshift.io_storageclients.yaml, cmd/main.go, config/crd/bases/ocs.openshift.io_storageclients.yaml, config/rbac/role.yaml, internal/controller/maintenancemode_controller.go, internal/controller/operatorconfigmap_controller.go, internal/controller/storageclaim_controller.go, internal/controller/storageclient_controller.go, pkg/utils/k8sutils.go, pkg/utils/predicates.go, service/status-report/main.go, vendor/github.com/red-hat-storage/ocs-client-operator/api/v1alpha1/storageclient_types.go
Depends on https://github.com/red-hat-storage/ocs-operator/pull/2870
A controller which will watch the StorageClient and MaintenanceMode CR by ramen to send a RequestMaintenaneMode RPC call to provider and set the status from response received from GetStorageConfig
=> controllers: new controller for maintenance mode

api/v1alpha1/storageclient_types.go, bundle/manifests/ocs-client-operator.clusterserviceversion.yaml, bundle/manifests/ocs.openshift.io_storageclients.yaml, config/crd/bases/ocs.openshift.io_storageclients.yaml
olm stops operator updates when a new field is introduced with a required qualifer, hence we need to make it optional
=> api: make inMaintenanceMode optional

bundle/manifests/ocs-client-operator.clusterserviceversion.yaml, config/rbac/role.yaml, internal/controller/storageclaim_controller.go, vendor/github.com/red-hat-storage/ocs-client-operator/api/v1alpha1/storageclient_types.go
Fix a typo for volumereplicationclasses because of which the container was not starting.
Followup for: https://github.com/red-hat-storage/ocs-client-operator/pull/276
=> controllers: fix typo for volumereplicationclasses

pkg/utils/k8sutils.go
The logs for operator had multiple StorageClaims reconcile for rbd type.
The VRC for flatten in rbd didn't have any annotation added to it due to which `reflect.DeepEqual` was treating it as difference and it was being created again and again. Hence moving to use `semantics.DeepQual` which treats empty and nil containers the same.
```
An empty slice *is* equal to a nil slice for our purposes; same for maps.
```
Ref: https://pkg.go.dev/k8s.io/apimachinery/third_party/forked/golang/reflect#Equalities.DeepEqual
=> controllers: use semantic deepequal

internal/controller/maintenancemode_controller.go
add an predicate.Or trigger reconcile of mmode controller when the storageClient's status is updated
=> controllers: fix predicate to trigger reconcile for mmode controller

internal/controller/storageclient_controller.go
set the client profile name in the mapping cr to be a hash of storageclaim name till we move to a single clientProfile for the entire client
=> controllers: set clientProfile name in mapping

internal/controller/storageclaim_controller.go
add a watch for storageClient annotation change in the claim controller
=> controllers: trigger reconcile for claims when the desired hash changes

internal/controller/storageclaim_controller.go
While offboarding the operator looks for VGSC's if the OCP feature gate is not enabled, the CRD won't be present and the operator won't proceed to offboarding. This PR checks if the VGSC CRD is present before looking for VGSC.
=> controllers: skip checking for vgsc if the crd is not present

internal/controller/operatorconfigmap_controller.go, pkg/templates/csi.go
The changes enables the nfs csi driver to be always deployed
=> controllers: always enable nfs csi driver

internal/controller/storageclient_controller.go
The secret are sent as map[string][]byte use map[string][]byte when unmarshalling the secret
=> controllers: use map[string][]byte to unmarsahll secrets

bundle/manifests/ocs-client-operator.clusterserviceversion.yaml, config/console/console_init.yaml
when an optional mount with subPath is used we are consistently observing failure at kubelet.
Error: container create failed: mount `/var/lib/kubelet/pods/<uid>/ volume-subpaths/ ocs-client-operator-console-nginx-conf/ ocs-client-operator-console/1` to `etc/nginx/nginx.conf`: Not a directory
we no longer need an `optional` mount for this configMap which only delays the starting of the container until CM is available but we no longer hit above issue.
=> bundle: remove optional mount for nginx-configmap

bundle/manifests/ocs-client-operator.clusterserviceversion.yaml, config/rbac/role.yaml, internal/controller/operatorconfigmap_controller.go
this is a tough find worthy of a explainer and here it goes
kubelet plugin registration mechanism:
watch a particular folder on node and for every sock creation send an rpc to get it registered and on sock deletion de-register the plugin
node driver registrar:
a sidecar in nodeplugin and on start create a sock when kubelet asks for the name gets the name from csi plugin and send to kubelet, when container is deleted this sidecar removes the sock (hostPath)
issue:
rook managed csi is running and already registered the csidrivers and on upgrade node registrar from csi-op managed csi tries to create the sock and doesn't error out as it already exists
however, due to the order of operations rook deletes it's csi and the sock in the host also gets deleted but node registrar doesn't create it …
=> sync between csi deletion by rook and csi creation by csi-operator

pkg/templates/csi.go
when client-op was created this field probably didn't exist (1.25) and when migration to csi-op is carried out only the existing fields from code was transferred.
this is a hint for Linux kernel that each volume is independently accessible and seems to be related to ReadWriteOncePod feature as well.
seLinuxMount is set to true in the yamls deployed by all ceph-csi (repo) supported drivers.
=> controllers: set csidriver.spec.seLinuxMount to true

internal/controller/storageclient_controller.go, service/status-report/main.go
move updating the channel annotation from heartbeat job to controller as the channel is already part of state hash and we reconcile when the hash changes.
Depends on #338
=> controllers: read subscription channel from GetDesiredClientState rpc

internal/controller/operatorconfigmap_controller.go, pkg/templates/csi.go
Disable CSI controller plugin host network when the client operator is running on the local storage cluster and the storage cluster is not on host network
=> controllers: disable csi ctrlPlugin hostNetwork for internal client

cmd/main.go, pkg/utils/k8sutils.go
Currently, the manager watches for resources in all namespaces. This ends up causing a increase in memory usage which hinders the regular deployment and activity of the operator, leading to the operator getting killed due to insufficient memory. 
The current proposed fix ensures that the manager caches resources from namespaces where the operator is deployed or that are specified in  the `WATCH_NAMESPACE` env variable.
Fixes: [DFBUGS-2056](https://issues.redhat.com/browse/DFBUGS-2056)  
-------------------------------------------------------------------------------------------------------------------------
After deploying the `ocs-client-operator`, various resources such as `ConfigMaps` and `Secrets` were created in a namespace different from the operator's own namespace.
* Behaviour …
=> restrict manager to watch selective  namespaces

cmd/main.go, internal/controller/storageclient_controller.go, pkg/utils/k8sutils.go, service/status-report/main.go
finding the operator version based on csv is erroneous at times and especially during upgrades when there is a possibility of two CSVs with same prefix in various phases.
since we don't set a name for pod in deployment it'll result in usual k8s naming convention and using that we go from pod -> dep -> csv -> ver
=> controllers: query the csvname based on operator deployment owner

bundle/manifests/ocs-client-operator.clusterserviceversion.yaml, config/rbac/status-reporter-clusterrole.yaml, service/status-report/main.go
Since we are sending the monips in the hash we no longer need to update the cephconnection from the status reporter, as a result, GetStorageConfig is no longer required from the status reporter
Fixes: https://issues.redhat.com/browse/DFBUGS-2359
=> controllers: stop calling GetStorageConfig from status reporter

internal/controller/storageclient_controller.go
In case of errors & unexpected situations the subscription channel returned  can be empty. We should not update the empty channel on the storageclient.
=> Avoid updating empty channel on the storage client annotations

bundle/manifests/ocs-client-operator.clusterserviceversion.yaml, config/rbac/role.yaml, internal/controller/storageclient_controller.go
*classes were missing update permissions add those permissions
Regression from: https://github.com/red-hat-storage/ocs-client-operator/pull/362
=> controllers: update missing permissions for classes

main.go, pkg/utils/k8sutils.go
Cache resources from namespaces where the operator is deployed or that are specified in  the `WATCH_NAMESPACE` env variable. 
(manual cherry pick from commit 4531319)
=> DFBUGS-2366: [release-4.16] restrict manager to watch selective namespaces

config/rbac/role.yaml, internal/controller/maintenancemode_controller.go, internal/controller/storageclient_controller.go
After the ownership of resources is transferred from `StorageClaim`, it remains in the cluster. This PR ensures that these `StorageClaims` are properly cleaned up.
Resolves: [DFBUGS-2625](https://issues.redhat.com/browse/DFBUGS-2625)
Test Results for `oc get storageclaim`:
- **Currently**:
```
NAME                          STORAGETYPE   STORAGEPROFILE   STORAGECLIENTNAME    PHASE
ocs-storagecluster-ceph-rbd   block                          ocs-storagecluster   Configuring
ocs-storagecluster-cephfs     sharedfile                     ocs-storagecluster   Configuring
```
- **With the fix**:
```
No resources found
```
=> controllers: delete StorageClaims post upgrade

.github/workflows/verify-generated.yaml
we were skipping this action from being run unintentionally due to wrong paths configured
=> ci: fix the paths in verify-generated action

internal/controller/storageclient_controller.go
The PR [#382](https://github.com/red-hat-storage/ocs-client-operator/pull/382) implemented deletion of StorageClaims as a part of the cleanup process. However, it did not account for scenarios where the StorageClaim kind is not present in the cluster. This is handled by the current PR.
Resolves: [DFBUGS-2625](https://issues.redhat.com/browse/DFBUGS-2625)
=> controllers: verify kind before deletion of StorageClaim

bundle/manifests/ocs-client-operator.clusterserviceversion.yaml, bundle/metadata/dependencies.yaml, config/metadata/dependencies.yaml, hack/build-catalog.sh, hack/make-bundle-vars.mk, internal/controller/operatorconfigmap_controller.go
add secondary name check for ex-snapshotter being "odf-external-snapshotter-operator"
=> csi: add secondary name check for ex-snapshotter

bundle/manifests/ocs-client-operator.clusterserviceversion.yaml, config/rbac/role.yaml, internal/controller/operatorconfigmap_controller.go
remove storageclient owned noobaa and noobaa csv, subscription managed by client-operator.
Taken from: https://github.com/red-hat-storage/ocs-client-operator/pull/407
Fixes: [DFBUGS-2807](https://issues.redhat.com//browse/DFBUGS-2807)
=> controllers: remove noobaa subscription if already present

bundle/manifests/ocs-client-operator.clusterserviceversion.yaml, bundle/metadata/dependencies.yaml, config/metadata/dependencies.yaml, config/rbac/role.yaml, internal/controller/operatorconfigmap_controller.go, internal/controller/storageclient_controller.go
we already have the feature to remove noobaa from client cluster in 4.19 and not required in 4.18
=> DFBUGS-2711:[release-4.18] Revert remove of noobaa from client cluster

bundle/manifests/ocs-client-operator.clusterserviceversion.yaml, config/rbac/role.yaml, internal/controller/operatorconfigmap_controller.go, internal/controller/storageclient_controller.go
requeue for storageclient owned noobaa and remove reconciliation in storageclient controller as older provider may still send noobaa and which the updated client shouldn't work on.
=> controllers: add watches for noobaa and remove reconciliation

bundle/manifests/ocs-client-operator.clusterserviceversion.yaml, config/rbac/role.yaml, internal/controller/operatorconfigmap_controller.go, internal/controller/storageclient_controller.go
requeue for storageclient owned noobaa and remove reconciliation in storageclient controller as older provider may still send noobaa and which the updated client shouldn't work on.
cherrypick of #428
=> DFBUGS-2640:[release-4.19] controllers: add watches for noobaa and remove reconciliation

internal/controller/storageclient_controller.go
log the reason for the precondition failure sent by hub.
=> controllers: fix reconciliation message with hub sent reason

internal/controller/operatorconfigmap_controller.go
Sets the SnapshotPolicy in `operatorconfig_controller` to be updated only when the (public) VolumeGroupSnapshotClass CRD exists.
=> controllers: reverting check for driverSpecDefaults

internal/controller/operatorconfigmap_controller.go, pkg/utils/slices.go
There can be an edge case during upgrades where there are two csv for noobaa pointing to different versions. This might result in only one csv being marked for deletion. We should be removing all the csv if they are not owned by the odf-op subs
=> controllers: delete all noobaa csvs

pkg/templates/csi.go
Use lower cpu, memory requqets for csi sidecars, to allow deployment in minimum supported lower spec clusters.
Ref: https://issues.redhat.com/browse/DFBUGS-4052
=> Use lower cpu, memory requests for csi sidecars
