bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
config/rbac/role.yaml
controllers/storageclassclaim_controller.go
controllers/storageclient_controller.go
main.go

Fixed RBAC and Status-reporter cron job creation and deletion.

Fix problems found in recent testing

---

bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
bundle/manifests/ocs.openshift.io_storageclassclaims.yaml
bundle/manifests/ocs.openshift.io_storageclients.yaml
config/default/kustomization.yaml

add the missing CRD files to the bundle.

bundle: add missing CRD to bundle

---

.github/workflows/verify-generated.yaml
Makefile
hack/gen-csi-images-manifest.sh
hack/make-bundle-vars.mk

The Action also runs on ubuntu and MacOS, because why not!
Signed-off-by: Jose A. Rivera <jarrpa@redhat.com>

Add GitHub Action for testing changes to CSI images

---

controllers/clusterversion_controller.go
controllers/suite_test.go

preserve the resourceVersion of the consolePlugin which is required for consolePlugin update.
BZ https://bugzilla.redhat.com/show_bug.cgi?id=2239608

preserve the resourceVersion of the consolePlugin

---

api/v1alpha1/storageclassclaim_types.go
config/crd/bases/ocs.openshift.io_storageclassclaims.yaml

add kubebuilder validations to make storageClassClaim spec immutable

api: make storageClassClaim immutable

---

pkg/csi/cephfsdaemonset.go
pkg/csi/cephfsdeployment.go
pkg/csi/rbddaemonset.go
pkg/csi/rbddeployment.go
pkg/templates/csisidecars.go

Remove the CSI container's resource requirements to align with internal mode.

csi: remove cpu & memory limits from sidecars

---

controllers/storageclassclaim_controller.go
controllers/storageclient_controller.go

a storageclassclaim can be attributed to a storageclient based on storageclient name and namespace, this commit makes sure to set annotations correctly.
fixes: #85

controllers: use annotations for claims and client mapping

---

OWNERS
api/v1alpha1/storageclassclaim_types.go
config/crd/bases/ocs.openshift.io_storageclassclaims.yaml
config/crd/bases/ocs.openshift.io_storageclients.yaml
config/rbac/role.yaml
controllers/clusterversion_controller.go
hack/make-bundle-vars.mk
hack/make-tools.mk
pkg/csi/csi.go
pkg/csi/rbddeployment.go
pkg/templates/csisidecars.go
pkg/templates/defaults.go

PR containing the latest commits from main branch

Syncing latest changes from main for ocs-client-operator

---

controllers/storageclassclaim_controller.go
pkg/csi/monconfigmap.go

This PR should be "code complete", but without the provider side merged there's no way to fully test it yet.
Depends on red-hat-storage/ocs-operator#2478
Signed-off-by: Jose A. Rivera <jarrpa@redhat.com>

storageclassclaim: check for and configure RADOS namespace

---

config/manager/kustomization.yaml
config/rbac/role.yaml
controllers/clusterversion_controller.go
main.go

if client-op is running along side with ocs-op and running in provider mode or client-op is in it's own cluster then only we should deploy CSI.
part of [RHSTOR-5487]

deploy CSI conditionally if client is running in provider mode or standalone

---

controllers/storageclient_controller.go

check if any other storageclient claimed ownership for creating default storageclaims, if none exist take ownership and create them if we didn't create them in previous reconcile already.
part of [RHSTOR-5553]
Depends on #116

create default storageclaim corresponding to storageclient

---

controllers/operatorconfigmap_controller.go

update ocs-client-operator subscription when all the storageclients agree to a single subscription channel.
part of [RHSTOR-5496]
Depends on #115

implement ocs-client-operator auto upgrade 

---

controllers/operatorconfigmap_controller.go

Create a deletion phase and delete the csi drivers and scc upon operator's removal as it is currently not being handled in the ClusterVersion controller.

Handle csi drivers and scc deletion

---

service/status-report/main.go

[RHSTOR-5500](https://issues.redhat.com/browse/RHSTOR-5500)
Setting the cluster's name that was exposed to the consumer's status in [#2534](https://github.com/red-hat-storage/ocs-operator/pull/2534).
- Refactor the `set`ters such that the code that fills in the fields is extracted into its own function
- Make the RBAC more restrictive

Setting the cluster's name

---

controllers/operatorconfigmap_controller.go

Addition to the based upon branch, adding a check to verify there is no PVs created by us prior deletion of the operator in order to prevent a scenario where dormant storage is present with no possible access by the user.

Add a deletion safegaurd mechanism for csi resources

---

config/manager/webhook_service.yaml
controllers/operatorconfigmap_controller.go
pkg/templates/webhookservice.go

remove webhook during deletion of configmap and reconcile webhook service which is deployed via bundle.
Depends on #80

reconcile webhook service and deletion of webhook

---

config/rbac/status-reporter-clusterrole.yaml
service/status-report/main.go

Rasing PR for 4.16, for Ref: https://github.com/red-hat-storage/ocs-client-operator/pull/151

Bug 2278593: [release-4.16] Setting basedomain as cluster name

---

.github/workflows/golangci-lint.yaml
pkg/csi/cephfsdaemonset.go
pkg/csi/cephfsdeployment.go
pkg/csi/rbddaemonset.go
pkg/csi/rbddeployment.go
pkg/templates/csisidecars.go

manual cherry-pick of #93. the change in golint version is not to always use latest rules against old code base.

Bug 2274675: [release-4.14] csi: remove cpu & memory limits from sidecars

---

bundle.Dockerfile
bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
bundle/metadata/annotations.yaml
config/manifests/bases/ocs-client-operator.clusterserviceversion.yaml
hack/make-tools.mk

CSV description and annotations required for the release are updated

bundle: update csv with info required for release

---

controllers/operatorconfigmap_controller.go

when ocs-client-op is upgraded by changing the channel name in the subscription (minor version) olm will not update the dependency to match the same channel. As we bring csi-addons as dep of ocs-client we will be updating the channel of csi-addons during reconcile.

controllers: ensure csi-addons sub channel matches ocs-client-op channel

---

.golangci.yaml
config/rbac/role.yaml
controllers/clusterversion_controller.go

this change will match csi-addons subscription channel with ocs-client-operator in 4.15

BUG 2276565: match csi-addons subscription channel to ocs-client-operator

---

service/deployment-guard/main.go

controllers: remove redundant code in init container

---

Dockerfile
Makefile
bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
config/console/console_init.yaml
config/console/kustomization.yaml
config/manager/kustomization.yaml
config/manager/manager.yaml
config/rbac/role.yaml
controllers/operatorconfigmap_controller.go
hack/go-build.sh
service/deployment-guard/main.go

manual cherry-pick of #196, #198

Bug 2300289: [release-4.16] init container to decide allowing reconciliation of manager

---

bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
bundle/metadata/dependencies.yaml
config/metadata/dependencies.yaml
hack/make-bundle-vars.mk

Required for https://github.com/red-hat-storage/odf-operator/pull/466

makefile: update csi-addons bundle version from 0.8.0 to 0.9.0

---

pkg/templates/csi.go

log rotation feature in csi-op provides a way to rotate csi logs based on custom configuration and this PR configures the default agreed upon values.

controllers: configure log rotater spec in csi-op operatorconfig

---

internal/controller/storageclaim_controller.go
internal/controller/storageclient_controller.go
service/status-report/main.go

updated storageclient connection fail log to show provider endpoint as well

controller: update storageclient connection fail log

---

bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
bundle/metadata/dependencies.yaml
config/metadata/dependencies.yaml
hack/make-bundle-vars.mk

- update noobaa version
- update cephcsi-operator version
- update the csi-addons version
- CSV from 4.17 to 4.18

bundle: update versions

---

internal/controller/storageclient_controller.go

Create the clientProfileMapping sent from the provider server required for DR

controllers: create clientprofilemapping required for DR

---

internal/controller/maintenancemode_controller.go

update the maintenance mode controller to put the storage clients in maintenance mode when a request is received

controllers: update maintenance mode controller

---

pkg/console/console.go

Fixes: https://issues.redhat.com/browse/RHSTOR-7079
Depends on: https://github.com/red-hat-storage/ocs-operator/pull/3047

console: add S3 proxy service declaration

---

internal/controller/operatorconfigmap_controller.go

along with other depedent operators of client-op we also need to update csi-op after client-op gets upgraded

controllers: update csi-op subscription based on provider version

---

internal/controller/storageclient_controller.go

storageconsumer is pre-created on the provider side and the token contains to which consumer current client should connect to and once connected (~onboarded) storageconfig is exchanged without any other intermediate step.

controllers: remove ack step from storageclient onboarding

---

internal/controller/storageclient_controller.go

add a watch on the crd by listening to it's creation dynamically. this effectively removes container restarts for establishing new watches.

controllers: add dynamic watches for volumesnapshotclass

---

internal/controller/storageclient_controller.go

these were the resources which were previously being reconciled by storageclaim controller and now moved to storageclient controller as they will now be sent as response for GetStorageConfig.

controllers: reconcile resources that will be part of GetStorageConfig

---

internal/controller/storageclient_controller.go

- we were unmarshalling the entire obj for clientProfile but we should only unmarshall the spec
- cephConnection name is sent form the provider server

controllers: fix clientProfile and cephConnection

---

internal/controller/storageclient_controller.go

currently we are using EnsureResource function for clusterscoped resources which tries to set Namespace for every reconcile but that fails when compared with live object everytime.
To not be ambiguous renamed the function and will change to work with generic objects when the need arise.
Credits: debugged w/ @rewantsoni

controllers: update secret data with received resource

---

internal/controller/storageclient_controller.go

the mutate function should have the unmarshall, setting of owner, adding the labels and annotations if we do it outside the mutate function the values won't be updated
Tested the changes with @leelavg and it works

controllers: fix ensureClusterScopedResources

---

go.mod
go.sum
vendor/golang.org/x/oauth2/oauth2.go
vendor/golang.org/x/oauth2/pkce.go
vendor/modules.txt

Fixes: https://issues.redhat.com/browse/DFBUGS-1993
CVE-2025-22868

Updated golang.org/x/oauth2 version from v0.24.0 to v0.27.0

---

internal/controller/storageclient_controller.go

from 4.19 we will use the new rpc call GetDesiredClientState to fetch the client info instead of GetStorageConfig

controllers: use GetDesiredClientState instead of GetStorageConfig

---

internal/controller/storageclient_controller.go
pkg/utils/k8sutils.go

Use createOrUpdate first, and if it fails with Forbidden then use createOrReplace
Fixes: https://issues.redhat.com/browse/DFBUGS-2289

controllers: don't replace the obj if it can be updated

---

internal/controller/operatorconfigmap_controller.go

when we run in hub then the management of subscriptions should be left to odf-operator or else we get stuck during upgrades due to the design of upgrading all dependents of odf-op in a single shot.
this commit doesn't reconcile webhook (and delete if exists) when we are running in hub.

controllers: manage webhook only if we are running standalone

---

bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
config/rbac/role.yaml
internal/controller/storageclient_controller.go

- Add vgrc to the kindsToReconcile
- Add permissions to reconcile VGRC sent by the provider
Depends on: https://github.com/red-hat-storage/ocs-operator/pull/3275
Fixes: https://issues.redhat.com/browse/DFBUGS-2673

controllers: reconcile vgrc sent by the provider

---

pkg/templates/csi.go

set default limits/request for all the containers in csi pods.

set default limits/requests for csi pods

---

internal/controller/storageclient_controller.go

During the upgrade there can be a race condition where client op is upgraded before ocs-op. Since we moved from csiop v1 from v1alpha1 in 4.20. This means that client-op in 4.20 will only reconcile api of version v1. This means that csiop api of version v1alpha1 will be deleted. To address this we are ignoring the api version while reconciling the resources.
Fixes: [DFBUGS-3863](https://issues.redhat.com/browse/DFBUGS-3863)

controllers: reconcile the resources by GK instead of GVK

---

bundle/manifests/ocs-client-operator.clusterserviceversion.yaml
config/rbac/role.yaml
internal/controller/storageclient_controller.go

Add the missing rbac for nfc
This was missed in https://github.com/red-hat-storage/ocs-client-operator/pull/475

controllers: add missing permissions for nfc
